### ISSUE TITLE
Add files to model without remplacing it

### ISSUE THREAD

**Issue by Nic0x** [aboutmydreams/custom_data_gpt#1]
Is it possible to train again (by adding more files) a model after already training it without remplacing the whole model?
Thank you

**Comment by aboutmydreams** [comment]
Maybe this function will help you
```python
store = FAISS.from_texts(docs, OpenAIEmbeddings())
store = store.add_embeddings(<your_text_embeddings>)
```

**Comment by Nic0x** [comment]
> Maybe this function will help you
> 
> ```python
> store = FAISS.from_texts(docs, OpenAIEmbeddings())
> store = store.add_embeddings(<your_text_embeddings>)
> ```

Can you be more specific? Which file should I modify? How to create text embeddings?
Thank you for your answer

**Comment by aboutmydreams** [comment]
> > Maybe this function will help you
> > ```python
> > store = FAISS.from_texts(docs, OpenAIEmbeddings())
> > store = store.add_embeddings(<your_text_embeddings>)
> > ```
> 
> Can you be more specific? Which file should I modify? How to create text embeddings? Thank you for your answer

Of course, the position of the code is 85 row in `main_api.py` . And you can see `add_embeddings` doc in FAISS api:
<img width="734" alt="image" src="https://github.com/aboutmydreams/custom_data_gpt/assets/34613360/095904c3-6c43-4983-ad70-972783bbc5fa">

Maybe [FAISS WIKI](https://github.com/facebookresearch/faiss/wiki) will help you

**Comment by Nic0x** [comment]
Thank you, I appreciate it
