### ISSUE TITLE
"error": "This model's maximum context length is 4097 tokens, however you requested 6539 tokens

### ISSUE THREAD

**Issue by Nic0x** [aboutmydreams/custom_data_gpt#2]
Everytime, I create new index based on a large file (20 pages pdf for ex.), I can't prompt it. Server return me this:
`"error": "This model's maximum context length is 4097 tokens, however you requested 6539 tokens (6283 in your prompt; 256 for the completion). Please reduce your prompt; or completion length."`

Even when my prompt is just "Hey". Any hints? Thank you

**Comment by aboutmydreams** [comment]
Need to give the minimum reproducible step

maybe the data which you use is not English?
